### ISSUE TITLE
iPhoneX identifier is missing

### ISSUE THREAD

**Issue by diegovilloutafredes** [dennisweissmann/DeviceKit#117] opened 2018-03-16 20:56 UTC
- iPhone10,6 identifier is missing from the enum cases.

**Comment by dennisweissmann** [comment] 2018-03-16 21:19
Is this a dupe of #115?

**Comment by diegovilloutafredes** [comment] 2018-03-16 21:34
Sorry, I just saw that and indeed is the same issue.

**Closed** 2018-03-16 22:18 UTC
